<?php include ($_SERVER["DOCUMENT_ROOT"]."/backend/blocks/metatags.php");
include ($_SERVER["DOCUMENT_ROOT"]."/src/html.blocks/header.html");
include ($_SERVER["DOCUMENT_ROOT"]."/src/html.blocks/callback.html");
include ($_SERVER["DOCUMENT_ROOT"]."/src/html.blocks/main.html");
include ($_SERVER["DOCUMENT_ROOT"]."/src/html.blocks/zakaz.html");
include ($_SERVER["DOCUMENT_ROOT"]."/src/html.blocks/steps.html");
include ($_SERVER["DOCUMENT_ROOT"]."/src/html.blocks/montazh-form.html");
include ($_SERVER["DOCUMENT_ROOT"]."/src/html.blocks/montazh.html");
include ($_SERVER["DOCUMENT_ROOT"]."/src/html.blocks/form.html");
include ($_SERVER["DOCUMENT_ROOT"]."/src/html.blocks/contacts.html");
include ($_SERVER["DOCUMENT_ROOT"]."/src/html.blocks/footer.html");
include ($_SERVER["DOCUMENT_ROOT"]."/backend/blocks/counters.html");